---
- name: Ensure old versions of Docker are not installed
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Install pre-requisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker apt key
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: false

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Force apt policy
  shell: >
    apt-cache policy docker-ce

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: "started"
    enabled: "true"
