name: Python Unit Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run PyTest
      run: |
        pip install -r test-requirements.txt
        pip install -r requirements.txt
        export PYTHONPATH=`pwd`
        pytest --cov=miner_config --cov-fail-under=80
