name: Run Blessed Block Update

on:
  push:
    branches:
     - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Python & dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-dev python3-pip -y
          sudo pip3 install -r requirements.txt
      - name: Clone upstream Helium Miner repository.
        run: |
          git clone https://github.com/helium/miner.git
      - name: Run config file generator.
        run: |
          PYTHONPATH=`pwd` python3 miner_config/generate_config.py
      - name: Setup gsutil.
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SA }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          export_default_credentials: true
      - name: Copy config file to bucket.
        run: |
          gsutil cp docker.config gs://helium-assets.nebra.com/docker.config
      - name: Set ACL
        run: |
          gsutil acl set acl.txt gs://helium-assets.nebra.com/docker.config
      - name: Purge Cloudflare Cache for URL
        run: |
          sleep 2m
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://helium-assets.nebra.com/docker.config",{"url":"https://helium-assets.nebra.com/docker.config"}]}'
