name: Run Blessed Block Update

on: [push] # This needs to be swapped to schedule once tested.

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Python & dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-dev python3-pip -y
          sudo pip3 install -r requirements.txt
      - name: Clone upstream Helium Miner repository.
        run: |
          git clone https://github.com/helium/miner.git
      - name: Run config file generator.
        run: |
          PYTHONPATH=`pwd` python3 miner_config/generate_config.py
      # Now upload the docker.config file to object storage + cdn.
