name: Run Blessed Block Update (Production)

on:
  push:
    branches:
     - production
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Install Python & dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-dev python3-pip -y
          sudo pip3 install -r requirements.txt
      - name: Run config file generator.
        run: |
          PYTHONPATH=`pwd` PRODUCTION=1 python3 miner_config/generate_config.py
          PYTHONPATH=`pwd` PRODUCTION=1 ROCKPI=1 python3 miner_config/generate_config.py
          # Output latest version info
          HEIGHT=$(curl -s -H 'Cache-Control: no-cache' https://storage.googleapis.com/helium-snapshots.nebra.com/latest.json | jq -r '.height')
          HASH=$(curl -s -H 'Cache-Control: no-cache' https://storage.googleapis.com/helium-snapshots.nebra.com/latest.json | jq -r '.hash')
          echo "Block height: $HEIGHT"
          echo "Block hash: $HASH"
          exit 0
      - name: Setup gsutil.
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SA }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          export_default_credentials: true
      - name: Copy config file to bucket.
        run: |
          gsutil cp docker.config gs://helium-assets.nebra.com/docker.config
          gsutil cp docker.config.rockpi gs://helium-assets.nebra.com/docker.config.rockpi
      - name: Set ACL
        run: |
          gsutil acl set acl.txt gs://helium-assets.nebra.com/docker.config
          gsutil acl set acl.txt gs://helium-assets.nebra.com/docker.config.rockpi
      - name: Change Cache-Control metadata of assets
        run: |
          gsutil setmeta -h "Cache-Control:max-age=60" gs://helium-assets.nebra.com/docker.config
          gsutil setmeta -h "Cache-Control:max-age=60" gs://helium-assets.nebra.com/docker.config.rockpi
          gsutil setmeta -h "Cache-Control:max-age=60" gs://helium-snapshots.nebra.com/latest.json
          gsutil setmeta -h "Cache-Control:max-age=60" gs://helium-snapshots.nebra.com/latest-snap.json
      - name: Purge Cloudflare Cache for URL
        run: |
          sleep 2m
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://helium-assets.nebra.com/docker.config",{"url":"https://helium-assets.nebra.com/docker.config"}]}'
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://helium-assets.nebra.com/docker.config.rockpi",{"url":"https://helium-assets.nebra.com/docker.config.rockpi"}]}'
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://helium-snapshots.nebra.com/latest.json",{"url":"https://helium-snapshots.nebra.com/latest.json"}]}'
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://helium-snapshots.nebra.com/latest-snap.json",{"url":"https://helium-snapshots.nebra.com/latest-snap.json"}]}'

