name: Run Blessed Block Update

on:
  push:
    branches:
     - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Python & dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-dev python3-pip -y
          sudo pip3 install -r requirements.txt
      - name: Clone upstream Helium Miner repository.
        run: |
          git clone https://github.com/helium/miner.git
      - name: Run config file generator.
        run: |
          PYTHONPATH=`pwd` python3 miner_config/generate_config.py
      # Here we test that the config actually works on a miner docker container...
      - name: Launch miner container.
        run: |
          docker pull quay.io/team-helium/miner:latest-amd64
          mkdir config
          cp docker.config config/sys.config
          docker run --volume config:/opt/miner/config -d --name miner quay.io/team-helium/miner:latest-amd64
      - name: Wait a couple of mins for the container to come up connect and start syncing.
        run: |
          sleep 2m
      - name: Compare the block height of the config file and the miner container.
        run: |
          PYTHONPATH=`pwd` python3 has_block_incremented.py
      - name: Stop miner container.
        run: |
          docker kill miner
          docker rm miner
      - name: Setup gsutil.
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_account_key: ${{ secrets.GOOGLE_SA }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          export_default_credentials: true
      - name: Copy config file to bucket.
        run: |
          gsutil cp docker.config gs://helium-assets.nebra.com/docker.config
      - name: Set ACL
        run: |
          gsutil acl set acl.txt gs://helium-assets.nebra.com/docker.config
